#
#  Travis-ci.org definition file for testing dRunner changes.
#  The actual tests are in the build script.
#
language: cpp
sudo: required

matrix:
   include:
     - os: linux
       dist: trusty
       sudo: required
#     - os: osx

before_install:
   - sudo bash .travis/install_docker.sh
   - docker run hello-world
script:
   - bash build fullinstall
   - drunner configure proxy=none
   - bash build check

after_success:
   - if [ $TRAVIS_BRANCH == 'master' ]; then bash build upload; fi
