platform:
  - x86

configuration:
  - Release

# Only clone the top level commit; don't bother with history
shallow_clone: true

install:
   - echo Installing POCO via conan
   - cmd: echo "Downloading conan..."
   - cmd: set PATH=%PATH%;%PYTHON%/Scripts/
   - cmd: pip.exe install conan
   - cmd: conan user # Create the conan data directory
   - cmd: conan --version
   - cmd: cd vs/conanrelease
   - cmd: conan install -s build_type=Release -s compiler="Visual Studio" -s compiler.runtime=MT -s arch=x86
   - cmd: cd ../..

build:
   project: vs\drunner.sln

# put in root folder for artifact, so S3 upload goes to root folder.
# See: http://help.appveyor.com/discussions/questions/1244-path-inside-artifact-name-is-there-a-way-to-remove-it
after_build:
   - ps: copy vs\Release\drunner.exe drunner.exe
# No docker on host.
#   - ps: drunner.exe initialise

artifacts:
   - path: drunner.exe
     name: drunner.exe

deploy:
  - provider: S3
    access_key_id:
      secure: m1Zla0GdyVcPtgii1OsDVIJum8LUMO2lj1BAMoYTqYo=
    secret_access_key:
      secure: Q9rvfslUVOEJv2WPoQ0qySKhGRBCk3ubjaUHWnigKAdpdybURrGXaO2GraEfKojE
    bucket: drunner
    folder: 10/win
    artifact: drunner.exe
    region: ap-southeast-2
    on:
       branch: master
